### PR TITLE
Refactor UOFile, preparing for lazy loading

### PR DESCRIPTION
**Pull request by MaxKellermann**
I want to implement lazy loading of assets, but that seems difficult because the code is so confusing; everything accesses internal variables. For lazy loading, I must hide internal variables behind a well-defined API, and this PR contains a few such pieces to get started.

### CODE REVIEW

**Comment by kamronbatman** [comment]
Yeah this is great. Thank you! I definitely agree we should lazy load / stream files.

**Review by kamronbatman — APPROVED** [review]

**Comment by MaxKellermann** [comment]
I'd prefer not to squash all commits in a PR, because I took great care to make separate commits; squashing loses a lot of information that may be important some day when somebody searches for a problem; and squashed commits cannot be bisected. That one big commit is a mess, but those 15 commits are easy to read.

**Comment by kamronbatman** [comment]
Ok Ill fix it next time I get to the computer. Most people have dirty commits so I squash, sorry about that.

EDIT: I fixed the squash by pushing the commits individually.

**Comment by MaxKellermann** [comment]
I know, people submit messy PRs - my policy as maintainer is to ask the submitter to clean up the mess before I merge, but I never squash-merge.

btw. you cherry-picked all the individual commits - this would have ben easier for you by just typing `git merge 1e0136` which creates a merge commit and preserves all the original commits - git can be so simple :-)

**Pull request merged**
